server:
  port: '8001'
spring:
  cloud:
    consul:
      discovery:
        instanceId: ms-service-a
        health-check-interval: 5s
service:
  b:
    url: http://ms-service-b/service/b


resilience4j:
  circuitbreaker:
    instances:
      menu-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 1
        slidingWindowSize: 10
        waitDurationInOpenState: 2s
        slidingWindowType: COUNT_BASED
