server:
  port: '8001'
spring:
  cloud:
    consul:
      discovery:
        instanceId: ms-service-a
        health-check-interval: 5s
service:
  b:
    url: http://ms-service-b/service/b

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
    health:
      show-details: always
    

resilience4j:
  circuitbreaker:
    instances:
        aInformation:
            registerHealthIndicator: true
            eventConsumerBufferSize: 10
            failureRateThreshold: 50
            minimumNumberOfCalls: 5
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 5s
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowSize: 10
            slidingWindowType: COUNT_BASED
